# Generated by Django 4.2 on 2023-05-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usage', models.TextField(blank=True, max_length=100, null=True)),
                ('medicine_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50, null=True)),
                ('last_pieces', models.IntegerField(blank=True, max_length=5, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
    ]
