# Generated by Django 4.2 on 2023-05-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='last_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
