# Generated by Django 4.2 on 2023-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_medicines_last_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
